variables:
  registryName: rippertesting
  imageName: ripper-drupal
  imageVersion: v1.0
  pass: $(dockerPassword)
trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Create image
    echo $(dockerPassword)
    docker build -t $(registryName).azurecr.io/$(imageName):$(imageVersion) .
    docker login -u $(registryName) -p $(pass) $(registryName).azurecr.io
    docker push $(registryName).azurecr.io/$(imageName):$(imageVersion)
