variables:
  registryName: rippertesting
  imageName: ripper-drupal
  imageVersion: v1.0
trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Create image
    docker build -t $(registryName).azurecr.io/$(imageName):$(imageVersion) .
    docker login -u $(registryName) -p $(pswd) $(registryName).azurecr.io
    docker push $(registryName).azurecr.io/$(imageName):$(imageVersion)
  env:
    pswd: $(dockerPassword)
